spring:
  config.import: file:./.env[.properties]
  application:
    name: TFintechGradProject
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

logging:
  level:
    org:
      springframework:
        security: TRACE
resilience4j:
  ratelimiter:
    instances:
      yandexMapsApi:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0s
  circuitbreaker:
    instances:
      yandexMapsApi:
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 100
        sliding-window-type: time_based

application:
  security:
    jwt:
      ttlRememberMe: 2592000000
      ttl: 600000
      secretKey: ${SECURITY_SECRET_KEY}

yandexMapsApi:
  apiKey: ${API_KEY}
  url: ${API_URL}
