spring:
  application:
    name: TFintechGradProject
  datasource:
    url: jdbc:postgresql://localhost:5432/tfintech_grad_project
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

yandexMapsApi:
  apiKey: 7ffff1e0-b2fc-4cfa-ac3c-18a27f1c71b5
  url: https://geocode-maps.yandex.ru/1.x/
