create table activities (
                            id bigint generated by default as identity,
                            category_id bigint not null,
                            name text not null unique,
                            primary key (id)
);

alter table if exists activities
    add constraint activity_category_fk
        foreign key (category_id) references activity_categories;