create table activity_requests (
                                   id bigint generated by default as identity,
                                   participants_required integer not null,
                                   activity_id bigint not null,
                                   address text,
                                   coordinates geography(POINT),
                                   comment text,
                                   primary key (id)
);