create table users (
                       id bigint generated by default as identity,
                       rating numeric(38,2) not null,
                       email text unique,
                       info text,
                       name text,
                       nickname text not null unique,
                       password text not null,
                       phone text not null unique,
                       primary key (id)
);